site_name: Sensitive Data Research Environment Documentation
  # docs_dir: 'docs/pages'
site_description: 'SDRE HPC wiki for end users/researchers'

nav:
  - Basics and General: 
      - Overview: pages/basics/overview.md
      - Account Request: pages/basics/account_request.md
      - Connecting to HPC: pages/basics/connect_to_hpc.md
      - System Specifications: pages/basics/system_specifications.md
      - Linux Introduction: pages/basics/linux_intro.md
      - SDRE User Policy: pages/basics/sdre_user_policy.md
  - High Performance Computing:
      - Using modules: placeholder.md
      - Standard Software Environment: placeholder.md
      - Using Slurm for running jobs: placeholder.md
      - Using GPUs with Slurm: placeholder.md
        #- How to use Easybuild: slurmintro.md
        #- How to use virtual environment: slurmintro.md
      - Install software in your home directory: placeholder.md
  - Storage and Data:
    - Storage Overview: placeholder.md
    - Scratch Space: placeholder.md
    - Data Transfer: placeholder.md
    - How to use Globus: placeholder.md
    - Quota Management: placeholder.md
  - Software Catalog:
    - Software Lists: placeholder.md
    - How to use Easybuild: placeholder.md
    - How to use virtual environment: placeholder.md
  - Related Links: place holder.md
  - Training/Learning Resources: 
    - Connecting to HPC: pages/training/connecting_to_hpc_video.md
    - Slurm Job Submission: pages/training/slurm_job_submission.md
    - Research Computing Bootcamp: pages/training/rc_bootcamp.md
  - FAQs: placeholder.md

theme:
  name: material
  favicon: images/favicon.png
    #palette:
    #scheme: default  # theme color (slate =dark mode)
    #primary: maroon
    #accent: pink
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.top
      #    - navigation.sections
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.download
    - content.tooltips
    - content.tabs
    - grid
    -
  logo: images/ua-logo.png

extra_css:
  - stylesheets/custom.css
    # - stylesheets/quicklinkcustom.css


markdown_extensions:
  - pymdownx.tabbed  # tab
  - pymdownx.superfences  # allow nested list
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list   #allow users to download files
  - admonition



