site_name: Sensitive Data Research Environment Documentation
  # docs_dir: 'docs/pages'
site_description: 'SDRE HPC wiki for end users/researchers'

nav:
  - Basics and General: 
      - Overview: pages/basics/overview.md
      - Account Request: pages/basics/account_request.md
      - Connecting to HPC: pages/basics/connect_to_hpc.md
      - System Specifications: pages/basics/system_specifications.md
      - Linux Introduction: pages/basics/linux_intro.md
      - SDRE User Policy: pages/basics/sdre_user_policy.md
  - High Performance Computing:
      - Using modules: pages/high_perf_computing/using_modules.md
      - Using Slurm for running jobs: pages/high_perf_computing/running_jobs.md
      - Using GPUs with Slurm: pages/high_perf_computing/using_gpus_with_slurm.md
        #- How to use Easybuild: slurmintro.md
        #- How to use virtual environment: slurmintro.md
      - Job arrays: pages/high_perf_computing/job_arrays.md
      - Resubmitting jobs: pages/high_perf_computing/resubmitting_jobs.md
      - Standard Software Environment: pages/high_perf_computing/standard_software_environment.md
  - Storage and Data:
    - Storage Overview: pages/storage_data/storage_overview.md
    - Data Transfer: pages/storage_data/data_transfer.md
    - Quota Management: pages/storage_data/quota_management.md
    - Data Governance: pages/storage_data/data_governance.md
  - Software Catalog:
    - Software Lists: pages/software_catalog/available_software.md
    - Available Python wheels: pages/software_catalog/available_python_wheels.md
    - Using Easybuild: pages/software_catalog/easybuild.md
    - Creating and using virtual environment: pages/software_catalog/virtual_environment.md
    - Using Apptainer Container: pages/software_catalog/apptainer.md
  - Related Links: 
    - Python: pages/related_links/python.md
    - Parallel Computing using Python Multiprocessing Module: pages/related_links/parallel_computing_python_multiprocessing.md
    - Matlab: pages/related_links/matlab.md
    - R: pages/related_links/r.md
    - Testing: pages/related_links/testing.md
  - Training/Learning Resources: 
    - Connecting to HPC: pages/training/connecting_to_hpc_video.md
    - Slurm Job Submission: pages/training/slurm_job_submission.md
    - Research Computing Bootcamp: pages/training/rc_bootcamp.md
  - System Status: pages/system_status/system_status.md
  - FAQs: placeholder.md

theme:
  name: material
  favicon: images/favicon.png
    #palette:
    #scheme: default  # theme color (slate =dark mode)
    #primary: maroon
    #accent: pink
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.instant
    - navigation.top
      #    - navigation.sections
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.download
    - content.tooltips
    - content.tabs
    - grid
    -
  logo: images/ua-logo.png

extra_css:
  - stylesheets/custom.css
    # - stylesheets/quicklinkcustom.css
  - stylesheets/button.css


markdown_extensions:
  - pymdownx.tabbed  # tab
  - pymdownx.superfences  # allow nested list
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list   #allow users to download files
  - admonition

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/accordition.js



